import { rolesArabicNames } from '@/lib/rolesArabicNames';
import {
  IconBox,
  IconUsers,
  IconUserCheck,
  IconBuildingStore,
  IconMapPins,
  IconBuildingCommunity,
  IconNeedle,
  IconColorFilter,
  IconCategoryFilled,
  IconShoppingBag,
  IconPackageExport,
  IconFileTypePdf,
  IconChartPie3,
  IconTrashFilled,
  IconPhotoFilled,
  IconTruckDelivery,
  IconPackages,
  IconFileSpreadsheet,
  IconRefresh,
} from '@tabler/icons-react';

interface NavSection {
  link: string;
  label: string;
  enLabel: string;
  icon: typeof IconBox;
  roles: (keyof typeof rolesArabicNames)[];
}

export const navSections: NavSection[] = [
  {
    link: '/statistics',
    label: 'الاحصائيات',
    enLabel: 'statistics',
    icon: IconChartPie3,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER', 'CLIENT'],
  },
  {
    link: '/home',
    label: 'المنتجات',
    enLabel: 'home',
    icon: IconBox,
    roles: ['ADMIN', 'SUPER_ADMIN', 'DATA_ENTRY', 'COMPANY_MANAGER', 'CLIENT'],
  },
  {
    link: '/orders',
    label: 'الطلبات',
    enLabel: 'invoices',
    icon: IconPackageExport,
    roles: Object.keys(rolesArabicNames) as (keyof typeof rolesArabicNames)[],
  },
  {
    link: '/orders-bulk-create',
    label: 'انشاء طلبات جماعية',
    enLabel: 'orders bulk create',
    icon: IconPackages,
    roles: ['ADMIN', 'SUPER_ADMIN', 'ACCOUNTANT', 'DATA_ENTRY'],
  },
  {
    link: '/orders-sheet',
    label: 'استيراد طلبات من اكسل',
    enLabel: 'orders sheet',
    icon: IconFileSpreadsheet,
    roles: ['ADMIN', 'SUPER_ADMIN', 'DATA_ENTRY'],
  },
  {
    link: '/orders-auto-apdate',
    label: 'التحديث التلقائي للطلبات',
    enLabel: 'orders auto update',
    icon: IconRefresh,
    roles: ['COMPANY_MANAGER'],
  },
  {
    link: '/clients',
    label: 'العملاء',
    enLabel: 'clients',
    icon: IconUsers,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'ACCOUNTANT',
      'DATA_ENTRY',
      'BRANCH_MANAGER',
    ],
  },
  {
    link: '/branches',
    label: 'الفروع',
    enLabel: 'branches',
    icon: IconUsers,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/tenants',
    label: 'الشركات',
    enLabel: 'tenants',
    icon: IconBuildingCommunity,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/reports',
    label: 'الكشوفات',
    enLabel: 'reports',
    icon: IconFileTypePdf,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'BRANCH_MANAGER',
      'ACCOUNTANT',
      'REPOSITORIY_EMPLOYEE',
      'CLIENT',
    ],
  },
  {
    link: '/locations',
    label: 'المناطق',
    enLabel: 'regions',
    icon: IconMapPins,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'BRANCH_MANAGER',
      'ACCOUNTANT',
      'DATA_ENTRY',
    ],
  },
  {
    link: '/agents-manifest',
    label: 'منافيست المندوبين',
    enLabel: 'agents manifest',
    icon: IconTruckDelivery,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'ACCOUNTANT',
      'BRANCH_MANAGER',
      'DATA_ENTRY',
    ],
  },
  {
    link: '/employees',
    label: 'الموظفين',
    enLabel: 'employees',
    icon: IconUserCheck,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'], // SHOULD ADD A NEW SCREEN TO ADD EMPLOYEES TO THE BRANCH MANAGER
  },
  {
    link: '/repositories',
    label: 'المخازن',
    enLabel: 'repositories',
    icon: IconBuildingStore,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'REPOSITORIY_EMPLOYEE',
      'BRANCH_MANAGER',
      'ACCOUNTANT',
    ],
  },
  {
    link: '/stores',
    label: 'المتاجر',
    enLabel: 'stores',
    icon: IconShoppingBag,
    roles: [
      'ADMIN',
      'SUPER_ADMIN',
      'DATA_ENTRY',
      'ACCOUNTANT',
      'BRANCH_MANAGER',
      'CLIENT',
    ],
  },
  {
    link: '/banners',
    label: 'البنرات',
    enLabel: 'banners',
    icon: IconPhotoFilled,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/deleted',
    label: 'المحذوفات',
    enLabel: 'deleted',
    icon: IconTrashFilled,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/categories',
    label: 'الاصناف',
    enLabel: 'categories',
    icon: IconCategoryFilled,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/sizes',
    label: 'الاحجام',
    enLabel: 'sizes',
    icon: IconNeedle,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
  {
    link: '/colors',
    label: 'الالوان',
    enLabel: 'colors',
    icon: IconColorFilter,
    roles: ['ADMIN', 'SUPER_ADMIN', 'COMPANY_MANAGER'],
  },
];
